//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EastRiverCommune.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public string ID { get; set; }
        public bool Enable { get; set; }
        public System.DateTime WhenModify { get; set; }
        public string Title { get; set; }
        public string CategoryID { get; set; }
        public string Content { get; set; }
        public string Address { get; set; }
        public System.DateTime RegistBeginDate { get; set; }
        public System.DateTime RegistEndDate { get; set; }
        public decimal Price { get; set; }
        public System.DateTime StartDate { get; set; }
        public int Days { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
