//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EastRiverCommune.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commodity
    {
        public Commodity()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public string ID { get; set; }
        public bool Enable { get; set; }
        public System.DateTime WhenModify { get; set; }
        public string Name { get; set; }
        public string CategoryID { get; set; }
        public decimal Price { get; set; }
        public string Unit { get; set; }
        public string PictruePath { get; set; }
        public string Description { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
